# The URL the site will be built for
base_url = "https://tirpitzia.life"

default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index
build_search_index = false

# Whether to generate feeds 
generate_feeds = true
feed_filenames = ["atom.xml"]

theme = "papaya"

[markdown]
# Whether to do syntax highlighting
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "material-dark", filename = "syntax-theme-dark.css" },
  { theme = "material-light", filename = "syntax-theme-light.css" },
]

[languages]

[languages.en]
title = "Your Name's Blog"
description = "A clean academic blog"
generate_feeds = true
feed_filenames = ["atom.xml"] 
taxonomies = [
    { name = "tags", feed = true, lang = "en" },
    { name = "categories", feed = true, lang = "en" },
]

[languages.en.translations]
projects = "Projects"
blog = "Blog"
about = "About"
recent_projects = "Recent Projects"
more_projects = "More Projects"
recent_blog_posts = "Recent Blog Posts"
more_blog_posts = "More blog posts"
tag = "Tag"
tags = "Tags"
to_all_tags = "To all tags"
category = "Category"
categories = "Categories"
to_all_categories = "To all categories"
view_by = "View by"
other = "Other"
minute = "min"
prev_page = "To newer posts"
next_page = "To older posts"
date_format = "%B %e, %Y"

[extra]
env = "ZOLA_ENV"
color_mode = "auto"
feed_filename = "atom.xml" 

menu_items = [
    { name = "blog", url = "$LANG_BASE_URL/blog", show_recent = true, recent_items = 3, recent_trans_key = "recent_blog_posts", more_trans_key = "more_blog_posts" },
    { name = "tags", url = "$LANG_BASE_URL/tags" },
    { name = "about", url = "$LANG_BASE_URL/about", show_recent = false },
]

[extra.images]
max_width = 2500

[extra.ogp]
locale = "en_US"
first_name = "Your"      
last_name = "Name"
gender = "female"   
username = "tirpitzia"      
image = ""               

[extra.social]
email = "your-email@example.com"
github = "tirpitzia"

[extra.cdn]
font_awesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"